apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-dashboard
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-dashboard
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: sentinel-dashboard
        release: default
    spec:
      restartPolicy: Always
      containers:
      - name: sentinel-dashboard
        image: zhxl1989/sentinel-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8719
          name: transport
        resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
        volumeMounts:
        - mountPath: /etc/localtime
          name: volume-localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-dashboard
  namespace: default
  labels:
    service: sentinel-dashboard
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30888
    - name: transport
      port: 8719
      protocol: TCP
      targetPort: 8719
      nodePort: 30899
  selector:
    app: sentinel-dashboard
  type: NodePort