apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-sentinel-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-sentinel-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: spring-cloud-sentinel-app
        release: default
    spec:
      restartPolicy: Always
      containers:
      - name: spring-cloud-sentinel-app
        image: zhxl1989/spring-cloud-sentinel-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9527
          name: http
        resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
        volumeMounts:
        - mountPath: /etc/localtime
          name: volume-localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
---
apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-sentinel-app
  namespace: default
  labels:
    service: spring-cloud-sentinel-app
spec:
  ports:
    - name: http
      port: 9527
      protocol: TCP
      targetPort: 9527
      nodePort: 30996
  selector:
    app: spring-cloud-sentinel-app
  type: NodePort